import numpy as np

# In competition settings these hyperparameters are fixed
BATCH_SIZE = 128
HIDDEN_SIZE_THIN = 2048
HIDDEN_SIZE_WIDE = 4096
LEARNING_RATE = 0.001
MAX_EPOCH = 3
MAX_EMBEDDING_DIM = 2048

EMBEDDINGS_DTYPE = np.float16
CLIENT_IDS_DTYPE = np.int64
NAME_EMBEDDING_DIM = 16

PAD_VALUE_SKU = 0
PAD_VALUE_CATEGORY = 0
PAD_VALUE_PRICE = 0
PAD_VALUE_NAME = np.zeros(NAME_EMBEDDING_DIM, dtype=np.float32)
PAD_VALUE_EVENT_TYPE = 0

MAX_SEQUENCE_LENGTH = 100

SKU_EMBEDDING_DIM = 32 * 4
CATEGORY_EMBEDDING_DIM = 16 * 2
EVENT_TYPE_EMBEDDING_DIM = 8 * 2

LSTM_HIDDEN_SIZE = 64 * 4
LSTM_NUM_LAYERS = 2
LSTM_DROPOUT = 0.1
LSTM_BIDIRECTIONAL = False